name: Build and deploy to DigitalOcean
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build container
      run: |
        docker build -t docker.pkg.github.com/richardthombs/freerangecampers.uk/freelancecampers-website:latest .

    - name: Push to registry
      run: |
        docker login docker.pkg.github.com -u richardthombs -p "${{secrets.GITHUB_TOKEN}}"
        docker push docker.pkg.github.com/richardthombs/freerangecampers.uk/freelancecampers-website:latest

  Deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      with:
        args: kubernetes cluster kubeconfig show gs2 > $GITHUB_WORKSPACE/.kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig -n freelancecampers delete deployment -l tier=website
        kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig -n freelancecampers apply -f k8s

    - name: Verify deployment
      run: |
        kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig -n freelancecampers -w --timeout=5m rollout status deployment freelancecampers-website
